name: to_string_helper_example
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  to_string_helper:

dependency_overrides:
  to_string_helper:
    path: ../to_string_helper

dev_dependencies:
  test: ^1.0.0


