# https://github.com/dart-lang/build/blob/master/build_config/README.md

targets:
  $default:
    builders:
      to_string_helper_generator|to_string_helper:
        enabled: true

builders:
  # BuilderDefinition
  to_string_helper:
    target: ":to_string_helper_generator"
    import: "package:to_string_helper_generator/builder.dart"
    builder_factories: ["toStringBuilder"]
    build_extensions: {".dart": [".to_string_helper.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
