name: to_string_helper_generator
version: 0.0.1
description: Generate code for package to_string_helper
homepage: https://github.com/zenonine/to_string_helper
repository: https://github.com/zenonine/to_string_helper/tree/master/generator

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0
