name: to_string_helper_example_with_generator
version: 1.0.0-beta

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  to_string_helper: ^1.0.0-beta

dev_dependencies:
  test: ^1.0.0

  build_runner: ^1.0.0
  to_string_helper_generator: ^1.0.0-beta

#dependency_overrides:
#  to_string_helper:
#    path: ../to_string_helper
#  to_string_helper_generator:
#    path: ../generator
