name: to_string_helper
version: 1.0.0-beta
description: Flexibly configure output of toString method (with or without code generation).
homepage: https://github.com/zenonine/to_string_helper
repository: https://github.com/zenonine/to_string_helper/tree/master/to_string_helper

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0
